[package]
name = "bridge-host-implementation"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
boxology = { workspace = true }
boxology-contract = { workspace = true }
boxology-runtime = { workspace = true }
boxology_generated_contract = { package = "bridge-host-contract", version = "=0.0.0", path = "../generated/contract" }
boxology_import_trigger_inbox = { package = "trigger-inbox-contract", version = "=0.0.0", path = "../../trigger-inbox/generated/contract" }
nix = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
