#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  pwd
)"

cd "$ROOT_DIR"

OUT_PATH="${1:-CODE_QUALITY_REPORT.md}"

have() { command -v "$1" >/dev/null 2>&1; }

git_sha="$(git rev-parse HEAD)"
git_commit_date="$(git show -s --format=%cs HEAD)"

rustc_version="$(rustc -V)"
cargo_version="$(cargo -V)"

scc_version="(missing: install scc)"
sloc_table_md="(missing: install scc)"
if have scc; then
  scc_version="$(scc --version)"
  sloc_table_md="$(
    scc --format json crates | python3 -c '
import json
import sys

data = json.load(sys.stdin)
tot = {"Count": 0, "Code": 0, "Blank": 0, "Comment": 0, "Complexity": 0}
rows = {}
for item in data:
    name = item["Name"]
    rows[name] = item
    for k in tot:
        tot[k] += int(item.get(k, 0) or 0)

def fmt_row(name, item):
    return f"| {name} | {item["Count"]} | {item["Code"]} | {item["Blank"]} | {item["Comment"]} | {item["Complexity"]} |"

print("| Language | Files | Code | Blank | Comments | Complexity |")
print("|---|---:|---:|---:|---:|---:|")
for name in sorted(rows.keys()):
    print(fmt_row(name, rows[name]))
print(fmt_row("Total", tot))
'
  )"
fi

llvm_cov_version="(missing: cargo-llvm-cov)"
if have cargo-llvm-cov || cargo llvm-cov --version >/dev/null 2>&1; then
  llvm_cov_version="$(cargo llvm-cov --version 2>/dev/null | head -n 1 || true)"
fi

cargo_audit_version="(missing: cargo-audit)"
cargo_audit_output="(cargo-audit not installed)"
if have cargo-audit || cargo audit --version >/dev/null 2>&1; then
  cargo_audit_version="$(cargo audit --version 2>/dev/null | head -n 1 || true)"
  set +e
  cargo_audit_output="$(cargo audit -q 2>&1)"
  audit_exit="$?"
  set -e
  if [ "$audit_exit" -ne 0 ]; then
    cargo_audit_output="$cargo_audit_output"$'\n'"(exit code: $audit_exit)"
  fi
fi

node_version="(missing: node)"
if have node; then
  node_version="$(node --version)"
fi

jscpd_version="(via npx)"

tests_total="$(
  cargo test --workspace --all-features --locked -- --list | python3 -c '
import sys

count = 0
for line in sys.stdin:
    line = line.strip()
    if line.endswith(": test"):
        count += 1
print(count)
'
)"

cat >"$OUT_PATH" <<EOF
# Code Quality Report — Crab Project

Generated for commit \`$git_sha\` (commit date: $git_commit_date).

This report is generated by \`scripts/gen_code_quality_report.sh\`.

## Tool Versions

- $rustc_version
- $cargo_version
- $scc_version
- $llvm_cov_version
- $cargo_audit_version
- node $node_version
- jscpd $jscpd_version

## Enforced Quality Gates

All required gates are defined in \`Makefile\` and enforced by CI in \`.github/workflows/quality.yml\`:

- \`cargo fmt --check\`
- \`cargo clippy -D warnings\`
- \`cargo check\` (dead code / unused warnings denied at workspace lint level)
- \`cargo test\`
- \`cargo llvm-cov\` gate: 100% lines + 100% functions, and 0 uncovered lines/functions
- \`jscpd\` duplication gate (threshold 0)

Canonical local command:

\`\`\`bash
make quality
\`\`\`

## Size (SLOC)

$sloc_table_md

## Tests

- Total tests (workspace): $tests_total

Note: test runtime is intentionally not recorded here because it is machine- and cache-dependent.

## Dependency Health (cargo-audit)

\`\`\`
$cargo_audit_output
\`\`\`
EOF

echo "Wrote $OUT_PATH"
